### ISSUE TITLE
Remove redundant json cast

### ISSUE THREAD

**Issue by felixlinker** [TechLabs-Berlin/H8-Identifier#13]
https://github.com/TechLabs-Berlin/H8-Identifier/blob/4bf261581ae90b63f25562db42d0879645ddb2ca/h8_identifier/yt_request.py#L34-L35

Why is this return value first transformed into a string and then back into an object? This seems unnecessary to me.

**Comment by thuyanh97** [comment]
@ZenVega the response itself is already a dict so we can delete those two lines and just take the response see #22. I didn't correct it for you because i don't know if you need the function as it is.

**Comment by ZenVega** [comment]
absolutely right. it's gone
