### ISSUE TITLE
Statically initiate vectorizer and svm

### ISSUE THREAD

**Issue by felixlinker** [TechLabs-Berlin/H8-Identifier#18]
https://github.com/TechLabs-Berlin/H8-Identifier/blob/4bf261581ae90b63f25562db42d0879645ddb2ca/h8_identifier/twitter_classifier/Anwendung.py#L51-L58

I would advise against initializing the `vectorizer` and `svm` on each call of this function. Why not initialize them as constants as you do with the regexes?

**Comment by thuyanh97** [comment]
Done thanks
