### ISSUE TITLE
Remove redundant json cast

### ISSUE THREAD

**Issue by felixlinker** [TechLabs-Berlin/H8-Identifier#22]
https://github.com/TechLabs-Berlin/H8-Identifier/blob/4bf261581ae90b63f25562db42d0879645ddb2ca/h8_identifier/twitter_classifier/url_to_hate.py#L56-L57

This cast from json to string to json is redundant. Why not simply use `response` directly?

**Comment by felixlinker** [comment]
Same with this cast:

https://github.com/TechLabs-Berlin/H8-Identifier/blob/4bf261581ae90b63f25562db42d0879645ddb2ca/h8_identifier/twitter_classifier/url_to_hate.py#L68-L69

**Comment by thuyanh97** [comment]
Done you were right, the response itself was a dict already
